# Generated by Django 3.0.5 on 2021-02-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AriaProfile',
            fields=[
                ('full_name', models.CharField(max_length=128, null=True)),
                ('f_name', models.CharField(max_length=64, null=True)),
                ('l_name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/profile/%Y/%m/%d/')),
                ('bio', models.CharField(max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
