# Generated by Django 3.1.7 on 2021-03-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aria_contact', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AriaProfile',
            fields=[
                ('full_name', models.CharField(max_length=128, null=True)),
                ('f_name', models.CharField(max_length=64, null=True)),
                ('l_name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/profile/%Y/%m/%d/')),
                ('bio', models.CharField(max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria_contact.contact')),
            ],
        ),
    ]
