# Generated by Django 3.1.3 on 2021-02-15 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('is_car', models.BooleanField(default=True)),
                ('car_type', models.IntegerField(choices=[(1, 'SEDAN'), (2, 'COUPE'), (3, 'SPORTS_CAR'), (4, 'STATION_WAGON'), (5, 'HATCHBACK'), (6, 'CONVERTIBLE'), (7, 'SUV'), (8, 'MINIVAN'), (9, 'PICKUP_TRUCK')], default=1, null=True)),
                ('vehicle_type', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='media/images/vehicles/%Y/%m/%d/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
