# Generated by Django 3.1.7 on 2021-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('image', models.ImageField(upload_to='services/categories/%Y/%m/%d/')),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
