# Generated by Django 3.1.7 on 2021-03-21 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=32, null=True)),
                ('street', models.CharField(max_length=128)),
                ('apartment_number', models.CharField(max_length=32, null=True)),
                ('pin_point_location', models.CharField(max_length=128, null=True)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
