# Generated by Django 3.1.3 on 2021-02-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aria_profile', '0001_initial'),
        ('aria_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria_profile.ariaprofile'),
        ),
    ]
