# Generated by Django 3.0.5 on 2021-02-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria_contact', '0002_contact_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile',
        ),
    ]
