# Generated by Django 3.1.3 on 2021-02-07 18:21

import aria.apps.car.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(1, 'SEDAN'), (2, 'COUPE'), (3, 'SPORTS_CAR'), (4, 'STATION_WAGON'), (5, 'HATCHBACK'), (6, 'CONVERTIBLE'), (7, 'SUV'), (8, 'MINIVAN'), (9, 'PICKUP_TRUCK')], default=1)),
                ('model', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='media/images/cars/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('type', models.IntegerField(choices=[(1, 'SEDAN'), (2, 'COUPE'), (3, 'SPORTS_CAR'), (4, 'STATION_WAGON'), (5, 'HATCHBACK'), (6, 'CONVERTIBLE'), (7, 'SUV'), (8, 'MINIVAN'), (9, 'PICKUP_TRUCK')], default=aria.apps.car.models.CarTypes['SEDAN'])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
        ),
    ]
